services:
  - type: web
    name: vindhu-preview
    env: python
    plan: free
    rootDirectory: ./
    buildCommand: pip install -r requirements.txt
    startCommand: python3 backend/https_server.py
    autoDeploy: true
