services:
  - type: static
    name: my-vindhu
    env: static
    buildCommand: echo "no build needed"
    staticPublishPath: static
    autoDeploy: true

    headers:
      - path: /modules/*
        name: Content-Type
        value: application/javascript
      - path: /*
        name: Cache-Control
        value: no-cache

    routes:
      - type: rewrite
        source: /*
        destination: /index.html
